version: "3"
services:
  node-app:
    build:
      context: .
    ports:
      - "3333:3333"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 91188982
      MYSQL_DATABASE: pcm
      MYSQL_USER: root
      MYSQL_PASSWORD: 91188982
    ports:
      - "3306:3306"
